# Generated by Django 3.1.1 on 2020-09-20 16:59

from django.db import migrations, models
import tweets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_auto_20200917_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=models.CharField(max_length=140, validators=[tweets.validators.validate_content]),
        ),
    ]
